#!/usr/bin/env node
// Generates host-language modules containing the canonical showcase ASTs.
// The generated module is loaded by the generated execution mode; no source template is parsed
// and no compiled/*.ast.json file is read on that request path.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('../../', import.meta.url).pathname;
const scenariosRoot = join(root, 'examples', 'site', 'scenarios');
const outputRoot = join(root, 'tools', 'showcase', 'adapters', 'generated');
const check = process.argv.includes('--check');

const scenarios = {};
for (const entry of readdirSync(scenariosRoot, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
  if (!entry.isDirectory() || !existsSync(join(scenariosRoot, entry.name, 'compiled', 'typescript', 'manifest.json'))) continue;
  const base = join(scenariosRoot, entry.name, 'compiled', 'typescript');
  const manifest = JSON.parse(readFileSync(join(base, 'manifest.json'), 'utf8'));
  scenarios[entry.name] = {};
  for (const [name, item] of Object.entries(manifest.templates)) {
    scenarios[entry.name][name] = JSON.parse(readFileSync(join(base, item.artifact), 'utf8'));
  }
}

const literal = JSON.stringify(scenarios, null, 2);
const header = '// Generated by tools/showcase/generate-native.mjs. Do not edit.\n';
const ts = `${header}import { basename } from 'node:path';\nimport type { Template } from '@polyspec/template';\n\nconst generated = ${literal} as Record<string, Record<string, Template>>;\n\nexport function generatedTemplates(root: string): Map<string, Template> {\n  const templates = generated[basename(root)];\n  if (!templates) throw new Error('generated templates are missing for ' + basename(root));\n  return new Map(Object.entries(templates));\n}\n`;
const js = `${header}import { basename } from 'node:path';\n\nconst generated = ${literal};\n\nexport function generatedTemplates(root) {\n  const templates = generated[basename(root)];\n  if (!templates) throw new Error('generated templates are missing for ' + basename(root));\n  return new Map(Object.entries(templates));\n}\n`;
const encoded = Object.fromEntries(Object.entries(scenarios).map(([id, templates]) => [id, Object.fromEntries(Object.entries(templates).map(([name, ast]) => [name, Buffer.from(JSON.stringify(ast)).toString('hex')]))]));
const goEntries = Object.entries(encoded).map(([id, templates]) => `\t${JSON.stringify(id)}: {${Object.entries(templates).map(([name, value]) => `${JSON.stringify(name)}: ${JSON.stringify(value)}`).join(', ')}},`).join('\n');
const go = `${header}package main\n\nimport (\n  "encoding/hex"\n  "fmt"\n  "path/filepath"\n  "github.com/polyspec/template/ast"\n  "github.com/polyspec/template/loader"\n)\n\nvar generatedNative = map[string]map[string]string{\n${goEntries}\n}\n\nfunc generatedArtifactLoader(root, language string) (*loader.MapLoader, error) {\n  entries, ok := generatedNative[filepath.Base(root)]\n  if !ok { return nil, fmt.Errorf("generated templates are missing for %s", filepath.Base(root)) }\n  result := loader.NewMapLoader(nil)\n  for name, encoded := range entries {\n    bytes, err := hex.DecodeString(encoded)\n    if err != nil { return nil, err }\n    tree, err := ast.DecodeTemplate(bytes)\n    if err != nil { return nil, err }\n    result.SetAST(name, tree)\n  }\n  return result, nil\n}\n`;
const rustEntries = Object.entries(encoded).map(([id, templates]) => `        ("${id}", &[${Object.entries(templates).map(([name, value]) => `("${name}", "${value}")`).join(', ')}])`).join(',\n');
const rust = `${header}use polyspec_template::{ast, loader::MapLoader};\nuse std::path::Path;\n\nfn decode_hex(input: &str) -> Result<Vec<u8>, String> {\n    (0..input.len()).step_by(2).map(|index| u8::from_str_radix(&input[index..index + 2], 16).map_err(|error| error.to_string())).collect()\n}\n\npub fn generated_loader(root: &Path) -> Result<MapLoader, String> {\n    let id = root.file_name().and_then(|value| value.to_str()).unwrap_or_default();\n    let entries = match id {\n${Object.entries(encoded).map(([id, templates]) => `        "${id}" => &[${Object.entries(templates).map(([name, value]) => `(\"${name}\", \"${value}\")`).join(', ')}][..],`).join('\n')}\n        _ => return Err(format!("generated templates are missing for {id}")),\n    };\n    let mut loader = MapLoader::new();\n    for (name, encoded) in entries {\n        let bytes = decode_hex(encoded)?;\n        let tree: ast::Template = serde_json::from_slice(&bytes).map_err(|error| error.to_string())?;\n        loader.set_ast(name, tree);\n    }\n    Ok(loader)\n}\n`;
const encodedJson = Buffer.from(JSON.stringify(encoded)).toString('base64');
const php = `<?php\n\ndeclare(strict_types=1);\n\nuse Polyspec\\Template\\Loader\\ArrayLoader;\n\nfunction generatedArtifactLoader(string $root): ArrayLoader\n{\n    $all = json_decode(base64_decode('${encodedJson}', true), true, 512, JSON_THROW_ON_ERROR);\n    $id = basename($root);\n    if (!isset($all[$id])) throw new RuntimeException('generated templates are missing for ' . $id);\n    $templates = [];\n    foreach ($all[$id] as $name => $encoded) $templates[$name] = json_decode(hex2bin($encoded), true, 512, JSON_THROW_ON_ERROR);\n    return new ArrayLoader($templates);\n}\n`;
mkdirSync(outputRoot, { recursive: true });
for (const [name, content, relativePath] of [
  ['native_templates.ts', ts, 'native_templates.ts'],
  ['native_templates.mjs', js, 'native_templates.mjs'],
  ['native_templates.go', go, '../go/native_templates.go'],
  ['native_templates.rs', rust, '../rust/src/native_templates.rs'],
  ['native_templates.php', php, 'native_templates.php'],
]) {
  const path = join(outputRoot, relativePath);
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) throw new Error(`[native] generated file is stale: ${name}`);
  } else writeFileSync(path, content);
}
process.stdout.write(`[native] ${check ? 'checked' : 'generated'} ${Object.keys(scenarios).length} scenario modules\n`);
