// Generated by tools/showcase/generate-direct.mjs. Do not edit.
package main

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/polyspec/template/functions"
	"github.com/polyspec/template/value"
)

func generatedLookup(ctx map[string]value.Value, root *value.OrderedMap, name string) value.Value {
	if item, ok := ctx[name]; ok { return item }
	item, _ := root.Get(name)
	return item
}
func generatedMember(item value.Value, key string) value.Value {
	if object, ok := item.(*value.OrderedMap); ok { value, _ := object.Get(key); return value }
	return nil
}
func generatedTruthy(item value.Value) bool { return value.IsTruthy(item) }
func generatedEcho(out *strings.Builder, item value.Value) error {
	text, err := value.Stringify(item); if err != nil { return err }; out.WriteString(functions.EscapeHTML(text)); return nil
}
func generatedDefault(args []value.Value) value.Value { if len(args) > 1 && value.IsTruthy(args[0]) { return args[0] }; if len(args) > 1 { return args[1] }; return nil }
func generatedCall(name string, args []value.Value) value.Value { if name == "default" { return generatedDefault(args) }; return nil }
func generatedUnary(op string, item value.Value) value.Value { if op == "!" { return !value.IsTruthy(item) }; return nil }
func generatedBinary(op string, left, right value.Value) value.Value { if op == "&&" { return value.IsTruthy(left) && value.IsTruthy(right) }; if op == "||" { return value.IsTruthy(left) || value.IsTruthy(right) }; return nil }
func generatedBlock(id, path, scenario string, root *value.OrderedMap, define DefineRegistry, scope map[string]value.Value) (string, error) {
	entry, ok := define.Get(id); if !ok { return "", nil }; typed, ok := entry.(DefineEntry); if !ok { return "", fmt.Errorf("generated define %s has invalid type", id) }; if typed.HTML != nil { return *typed.HTML, nil }; target := path; if typed.Template != nil { target = *typed.Template }; context := map[string]value.Value{}; for _, key := range root.Keys() { item, _ := root.Get(key); context[key] = item }; if typed.Data != nil { for _, key := range typed.Data.Keys() { item, _ := typed.Data.Get(key); context[key] = item } }; for key, item := range scope { context[key] = item }; return generatedTemplate(target, scenario, root, define, context)
}
func generatedTemplate(name, scenario string, root *value.OrderedMap, define DefineRegistry, parent map[string]value.Value) (string, error) {
	switch scenario {
	case "empty-state":
		switch name {
		case "layout.tpl": return generated_empty_state__layout_tpl(root, define, parent)
		default: return "", fmt.Errorf("generated template is missing: %s", name)
		}
	case "html-slot":
		switch name {
		case "layout.tpl": return generated_html_slot__layout_tpl(root, define, parent)
		default: return "", fmt.Errorf("generated template is missing: %s", name)
		}
	case "scope-precedence":
		switch name {
		case "content.tpl": return generated_scope_precedence__content_tpl(root, define, parent)
		case "layout.tpl": return generated_scope_precedence__layout_tpl(root, define, parent)
		default: return "", fmt.Errorf("generated template is missing: %s", name)
		}
	default: return "", fmt.Errorf("generated scenario is missing: %s", filepath.Base(scenario))
	}
}
func generatedDirectRender(rootPath string, request RenderRequest) (string, error) {
	entry, ok := request.Define.Get(request.Target); name := request.Target; if ok { if path, isPath := entry.(string); isPath { name = path } else if typed, isTyped := entry.(DefineEntry); isTyped && typed.Template != nil { name = *typed.Template } }; return generatedTemplate(name, filepath.Base(rootPath), request.Assign, request.Define, map[string]value.Value{})
}

func generated_empty_state__layout_tpl(root *value.OrderedMap, define DefineRegistry, parent map[string]value.Value) (string, error) {
	ctx := map[string]value.Value{}
	for key, item := range parent { ctx[key] = item }
	var out strings.Builder
	out.WriteString("<main class=\"empty-page\">\n")
	if _, ok := define.Get("content"); ok {
		blockScope := map[string]value.Value{}
		blockHTML, err := generatedBlock("content", "", "empty-state", root, define, blockScope)
		if err != nil { return "", err }
		out.WriteString(blockHTML)
	} else {
		out.WriteString("<p class=\"empty\">No content definition.</p>\n")
	}
	out.WriteString("</main>\n")
	return out.String(), nil
}

func generated_html_slot__layout_tpl(root *value.OrderedMap, define DefineRegistry, parent map[string]value.Value) (string, error) {
	ctx := map[string]value.Value{}
	for key, item := range parent { ctx[key] = item }
	var out strings.Builder
	out.WriteString("<section class=\"notice\">\n<h1>")
	if err := generatedEcho(&out, generatedLookup(ctx, root, "heading")); err != nil { return "", err }
	out.WriteString("</h1>\n")
	blockScope := map[string]value.Value{}
	blockHTML, err := generatedBlock("content", "", "html-slot", root, define, blockScope)
	if err != nil { return "", err }
	out.WriteString(blockHTML)
	out.WriteString("</section>\n")
	return out.String(), nil
}

func generated_scope_precedence__content_tpl(root *value.OrderedMap, define DefineRegistry, parent map[string]value.Value) (string, error) {
	ctx := map[string]value.Value{}
	for key, item := range parent { ctx[key] = item }
	var out strings.Builder
	out.WriteString("<article>\n<h1>")
	if err := generatedEcho(&out, generatedLookup(ctx, root, "title")); err != nil { return "", err }
	out.WriteString("</h1>\n<p class=\"root\">")
	if err := generatedEcho(&out, generatedLookup(ctx, root, "root_label")); err != nil { return "", err }
	out.WriteString("</p>\n<p class=\"defined\">")
	if err := generatedEcho(&out, generatedLookup(ctx, root, "defined_label")); err != nil { return "", err }
	out.WriteString("</p>\n<p class=\"local\">")
	if err := generatedEcho(&out, generatedCall("default", []value.Value{generatedLookup(ctx, root, "layout_local"), "missing"})); err != nil { return "", err }
	out.WriteString("</p>\n</article>\n")
	return out.String(), nil
}

func generated_scope_precedence__layout_tpl(root *value.OrderedMap, define DefineRegistry, parent map[string]value.Value) (string, error) {
	ctx := map[string]value.Value{}
	for key, item := range parent { ctx[key] = item }
	var out strings.Builder
	ctx["layout_local"] = "visible only in layout"
	out.WriteString("<section class=\"scope\">\n")
	blockScope := map[string]value.Value{}
	blockScope["title"] = generatedMember(generatedLookup(ctx, root, "page"), "title")
	blockHTML, err := generatedBlock("content", "", "scope-precedence", root, define, blockScope)
	if err != nil { return "", err }
	out.WriteString(blockHTML)
	out.WriteString("</section>\n")
	return out.String(), nil
}
