// Code generated by scripts/generate-showcase-contract.mjs. DO NOT EDIT.
package main

import "github.com/polyspec/template/value"

type JsonValue = value.Value
type JsonObject = *value.OrderedMap
type DefineRegistry = *value.OrderedMap

type DefineEntry struct {
	Template *string
	Data     JsonObject
	HTML     *string
}

type Environment struct {
	Timezone *string
	Now      *float64
}

type Scenario struct {
	Target string
	Assign JsonObject
	Define DefineRegistry
	Env    *Environment
}

type RenderRequest struct {
	Target string
	Assign JsonObject
	Define DefineRegistry
	Env    *Environment
}

type RepeatResult struct {
	First  string
	Second string
}

type RenderAdapter interface {
	LoadScenario() (Scenario, error)
	BuildRequest(Scenario) (RenderRequest, error)
	Render(RenderRequest) (string, error)
	RenderTwice(RenderRequest) (RepeatResult, error)
}
