// Generated by tools/showcase/generate-direct.mjs. Do not edit.
use crate::render_adapter::{DefineRegistry, RenderRequest};
use serde_json::{Map, Value};
use std::path::Path;

fn generated_lookup(ctx: &Map<String, Value>, root: &Map<String, Value>, name: &str) -> Value { ctx.get(name).cloned().or_else(|| root.get(name).cloned()).unwrap_or(Value::Null) }
fn generated_member(value: Value, key: &str) -> Value { value.as_object().and_then(|map| map.get(key)).cloned().unwrap_or(Value::Null) }
fn generated_truthy(value: &Value) -> bool { match value { Value::Null => false, Value::Bool(value) => *value, Value::Number(value) => value.as_f64().unwrap_or(0.0) != 0.0, Value::String(value) => !value.is_empty(), Value::Array(value) => !value.is_empty(), Value::Object(value) => !value.is_empty() } }
fn generated_string(value: Value) -> Result<String, String> { match value { Value::Null => Ok(String::new()), Value::Bool(value) => Ok(value.to_string()), Value::Number(value) => Ok(value.to_string()), Value::String(value) => Ok(value), Value::Array(_) | Value::Object(_) => Err("a collection cannot be converted to text".to_string()) } }
fn generated_escape(value: Value) -> Result<String, String> { Ok(generated_string(value)?.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;").replace('\"', "&quot;").replace("'", "&#39;")) }
fn generated_echo(out: &mut String, value: Value) -> Result<(), String> { out.push_str(&generated_escape(value)?); Ok(()) }
fn generated_call(name: &str, args: Vec<Value>) -> Value { if name == "default" && args.len() > 1 { if generated_truthy(&args[0]) { args[0].clone() } else { args[1].clone() } } else { Value::Null } }
fn generated_block(id: &str, path: &str, scenario: &str, root: &Map<String, Value>, define: &DefineRegistry, scope: &Map<String, Value>) -> Result<String, String> {
    let Some(entry) = define.get(id) else { return Ok(String::new()) };
    if let Some(html) = &entry.html { return Ok(html.clone()) }
    let target = entry.template.as_deref().unwrap_or(path);
    let mut context = root.clone();
    if let Some(data) = &entry.data { context.extend(data.clone()) }
    context.extend(scope.clone());
    generated_template(target, scenario, root, define, &context)
}
fn generated_template(name: &str, scenario: &str, root: &Map<String, Value>, define: &DefineRegistry, parent: &Map<String, Value>) -> Result<String, String> {
    match scenario {
        "empty-state" => match name {
            "layout.tpl" => generated_empty_state__layout_tpl(root, define, parent),
            _ => Err(format!("generated template is missing: {name}")),
        },
        "html-slot" => match name {
            "layout.tpl" => generated_html_slot__layout_tpl(root, define, parent),
            _ => Err(format!("generated template is missing: {name}")),
        },
        "scope-precedence" => match name {
            "content.tpl" => generated_scope_precedence__content_tpl(root, define, parent),
            "layout.tpl" => generated_scope_precedence__layout_tpl(root, define, parent),
            _ => Err(format!("generated template is missing: {name}")),
        },
        _ => Err(format!("generated scenario is missing: {}", Path::new(scenario).file_name().and_then(|v| v.to_str()).unwrap_or(scenario))),
    }
}
pub fn generated_direct_render(root_path: &Path, request: &RenderRequest) -> Result<String, String> {
    let name = request.define.get(&request.target).and_then(|entry| entry.template.clone()).unwrap_or_else(|| request.target.clone());
    generated_template(&name, root_path.file_name().and_then(|v| v.to_str()).unwrap_or_default(), &request.assign, &request.define, &Map::new())
}

fn generated_empty_state__layout_tpl(root: &Map<String, Value>, define: &DefineRegistry, parent: &Map<String, Value>) -> Result<String, String> {
    let mut ctx = parent.clone();
    let mut out = String::new();
    out.push_str("<main class=\"empty-page\">\n");
    if define.contains_key("content") {
        let mut block_scope = Map::new();
        out.push_str(&generated_block("content", "", "empty-state", root, define, &block_scope)?);
    } else {
        out.push_str("<p class=\"empty\">No content definition.</p>\n");
    }
    out.push_str("</main>\n");
    Ok(out)
}

fn generated_html_slot__layout_tpl(root: &Map<String, Value>, define: &DefineRegistry, parent: &Map<String, Value>) -> Result<String, String> {
    let mut ctx = parent.clone();
    let mut out = String::new();
    out.push_str("<section class=\"notice\">\n<h1>");
    generated_echo(&mut out, generated_lookup(&ctx, root, "heading"))?;
    out.push_str("</h1>\n");
    let mut block_scope = Map::new();
    out.push_str(&generated_block("content", "", "html-slot", root, define, &block_scope)?);
    out.push_str("</section>\n");
    Ok(out)
}

fn generated_scope_precedence__content_tpl(root: &Map<String, Value>, define: &DefineRegistry, parent: &Map<String, Value>) -> Result<String, String> {
    let mut ctx = parent.clone();
    let mut out = String::new();
    out.push_str("<article>\n<h1>");
    generated_echo(&mut out, generated_lookup(&ctx, root, "title"))?;
    out.push_str("</h1>\n<p class=\"root\">");
    generated_echo(&mut out, generated_lookup(&ctx, root, "root_label"))?;
    out.push_str("</p>\n<p class=\"defined\">");
    generated_echo(&mut out, generated_lookup(&ctx, root, "defined_label"))?;
    out.push_str("</p>\n<p class=\"local\">");
    generated_echo(&mut out, generated_call("default", vec![generated_lookup(&ctx, root, "layout_local"), Value::String("missing".to_string())]))?;
    out.push_str("</p>\n</article>\n");
    Ok(out)
}

fn generated_scope_precedence__layout_tpl(root: &Map<String, Value>, define: &DefineRegistry, parent: &Map<String, Value>) -> Result<String, String> {
    let mut ctx = parent.clone();
    let mut out = String::new();
    ctx.insert("layout_local".to_string(), Value::String("visible only in layout".to_string()));
    out.push_str("<section class=\"scope\">\n");
    let mut block_scope = Map::new();
    block_scope.insert("title".to_string(), generated_member(generated_lookup(&ctx, root, "page"), "title"));
    out.push_str(&generated_block("content", "", "scope-precedence", root, define, &block_scope)?);
    out.push_str("</section>\n");
    Ok(out)
}
