// Generated by scripts/generate-showcase-contract.mjs. Do not edit.
use indexmap::IndexMap;
use serde::Deserialize;
use serde_json::{Map, Value};

pub type JsonValue = Value;
pub type JsonObject = Map<String, JsonValue>;
pub type DefineRegistry = IndexMap<String, DefineEntry>;

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DefineEntry {
    pub template: Option<String>,
    pub data: Option<JsonObject>,
    pub html: Option<String>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Environment {
    pub timezone: Option<String>,
    pub now: Option<f64>,
}

#[derive(Clone, Debug)]
pub struct Scenario {
    pub target: String,
    pub assign: JsonObject,
    pub define: DefineRegistry,
    pub env: Option<Environment>,
}

#[derive(Clone, Debug)]
pub struct RenderRequest {
    pub target: String,
    pub assign: JsonObject,
    pub define: DefineRegistry,
    pub env: Option<Environment>,
}

#[derive(Clone, Debug)]
pub struct RepeatResult {
    pub first: String,
    pub second: String,
}

pub trait RenderAdapter {
    fn load_scenario(&self) -> Result<Scenario, String>;
    fn build_request(&self, scenario: &Scenario) -> Result<RenderRequest, String>;
    fn render(&self, request: &RenderRequest) -> Result<String, String>;
    fn render_twice(&self, request: &RenderRequest) -> Result<RepeatResult, String>;
}
